BuddiesOfBudgie/budgie-desktop

src/panel/settings/settings_panel_applets.vala
Reported by @fossfreedom on the old repository (https://github.com/solus-project/budgie-desktop/issues/2189). This simply reset the selection state and disable the controls after deleting.
=> Prevent crash when deleting twice the same applet

src/applets/notifications/NotificationsApplet.vala, src/daemon/notifications/dbus.vala, src/raven/notifications_view.vala, src/raven/raven.vala
This removes our dependence on GNOME settings schemas for Do Not Disturb functionality (again). I decided to make this a PR to get other eyes on it in case there's something I missed.
=> Don't use the notification settings for DND

src/panel/budgie-desktop-settings.desktop.in
Please refer to
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html,
Bug#693918, and
https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords for details.
This resolve reported lintian issues in Debian packaging.
=> Add keywords to budgie-desktop-settings.desktop

src/wm/20_solus-project.budgie.wm.gschema.override
ubuntu 22.04:
compiling gschema produces the following error:
```
Error parsing key “switch-input-source” in schema “org.gnome.desktop.wm.keybindings:Budgie” as specified in override file “/usr/share/glib-2.0/schemas/20_solus-project.budgie.wm.gschema.override”: 0-56:can not parse as value of type 'as'. Ignoring override for this key.
Error parsing key “switch-input-source-backward” in schema “org.gnome.desktop.wm.keybindings:Budgie” as specified in override file “/usr/share/glib-2.0/schemas/20_solus-project.budgie.wm.gschema.override”: 0-52:can not parse as value of type 'as'. Ignoring override for this key.
```
This means that our switch-input overrides are ignored and the default GNOME overrides are used instead.
Verified that glib-compile-schema no longer errors and dconf-editor shows …
=> Ensure gschema override for switch-input-source* is formatted correctly.

src/daemon/notifications/dbus.vala, src/daemon/notifications/popup.vala, src/lib/notification.vala
Before this commit, Firefox would show its own notification popups whenever Budgie notifications or popups were paused or disabled. This seems to fix that issue: when notifications are paused, no popups of any kind are shown.
I have no idea why this matters to Firefox, nor how it even detects it, but so far it seems to be working.
This also matches what the Budgie notification server used to do before the rewrite. Previously the expiry variable was set to 0 and all was right with the world.
=> Fix some applications showing their own notification popups when paused

src/raven/notifications_view.vala
Since the notifications rewrite, the button to trigger Do Not Disturb would sometimes not be shown.
This ensures that it always starts with an icon, and is thus shown.
=> Fix notification mute button sometimes starting without an image

src/theme/3.20/_main.scss, src/theme/common/_switcher.scss
Restyles the tab switcher (alt-tab) in the built-in theme to fit with the rest of the dialogs.
=> Update tab switcher style for built-in theme

src/wm/keyboard.vala
Closes: #56
When budgie-wm is used with non ibus input method,
It causes a SEGV unexpectedly.
There are two vectors to cause this situation.
* Array<InputSource> is not initialized explicitly, but it may be
accessed unexpectedly.
* Array<InputSource> may be empty, thus it causes arithmetic exception
with "% sources.length"
* Use non ibus input method (e.g. fcitx5)
* Type Alt+Shift_L twice or so
PR fixes the issue on Debian unstable with budgie-desktop_10.5.3+git20220217a-1 (with this patch)
=> Fix SEGV when input source was switched by Alt+Shift_L

src/raven/main_view.vala
Per the answer [here](https://stackoverflow.com/questions/22178524/gtk-named-stack-childs), if a stack child is not visible, asking the stack to set the visible child will silently fail, apparently even if the child being shown *is* visible.
The NotificationView widget already calls `show_all()` in its constructor, so the call only had to be added to the applet window. This fixes the case where clicking the notification bell fails to open the correct page, and possibly also fixes where clicking the Raven trigger for the first time sometimes fails to open Raven (it is technically open, but the elements aren't visible).
Thanks to @fossfreedom for finding that link!
Fixes #31
=> Fix inconsistency when opening Raven

src/applets/icon-tasklist/IconButton.vala, src/applets/icon-tasklist/IconTasklistApplet.vala
This pull request moves icon scaling within the icon tasklist from the applet itself to each of the buttons, and provides a smooth scaling gradient for those icons between different panel sizes. Icon updates are now done on button size allocation, and only if the new allocation differs from the old allocation.
Icons would resize in predetermined steps, such as 24px to 48px to 96px.
https://user-images.githubusercontent.com/12981608/157320723-7db1d048-106b-457c-b035-1e92e4bf5fae.mp4
Icons sourced by gicons are now scaled to a target size that approximates 2/3 of the size of the panel itself, up to an icon size of 54px, where it shifts to the panel size minus 18. This allows for icons to scale to much smaller and much larger sizes, while retaining desirable icon sizes for dock setups, and …
=> Proper icon tasklist scaling

src/raven/notifications_group.vala
This prevents a critical message when dismissing notification groups. When iterating over a HashTable using the `foreach` method, the table should not be modified. Instead, use `foreach_steal` to iterate and remove from the notifications table.
=> Don't modify notification group HashTables while iterating over them

src/daemon/notifications/dbus.vala, src/daemon/notifications/popup.vala
There is a race condition where a notification may be closed and in the process of destruction, and a new notification is requested to be shown right after. This causes the position calculation to fail because the existing popup is no longer a Widget, but it's also not `null`.
This problem is addressed here by adding a boolean property to the popup widget that is set to `true` when `dismiss()` is called on it, and checking that property when we want to position a new notification. Additionally, move the latest notification check out of the `switch` branches, and getting our needed values as soon as possible.
=> Improve racyness when a notification is closed and another one shown in quick succession

src/abomination/abomination.vala, src/applets/icon-tasklist/IconTasklistApplet.vala
This was introduced in Abomination in an attempt to fix Chrome profile manager closing sequence but ended up breaking some other apps (such as Steam) closing sequence.
Instead, try to re-parent first app of group when an app associated with a pinned icon is closed so that the pinned button is reused.
Fixes #85
=> Remove delay in Abomination when opening apps

src/abomination/RunningApp.vala, src/applets/icon-tasklist/DesktopHelper.vala, src/applets/icon-tasklist/IconButton.vala, src/applets/icon-tasklist/IconTasklistApplet.vala
This was due to the incorrect app ID being passed to the signal handler.
Instead we can pass the correct ID that we determine in IconTasklistApplet when instanciating the button.
This revert last attempt to fix the issue as it was causing other issues with Budgie settings and LibreOffice (and quite possibly the issue reported by @serebit in #93)
=> Fix regression where non pinned icons were not reorderable in icon tasklist

src/panel/manager.vala, src/panel/panel.vala
Includes autohide policy (Autohide: enum), transparency (Transparency: enum), dock mode (Dock: boolean), and shadow visibility (Shadow: boolean).
Additionally, this PR removes the ability to set panel transparency via a gsettings override. Downstreams that use this method to change default panel transparency will need to ship a modified panel.ini instead.  
Resolves #88.
=> Add more panel config options to panel.ini

meson.build
This PR is a simple change that sets `warning_level` to 3 across the entire project, with an override for the gvc subproject to a `warning_level` of 0 (as we can't fix any of these warnings due to it being a subproject, there's no real point in printing them). Additionally, we now set the project_name and project_version args when compiling gvc.This results in a reduction in compile log lines from 879 to 546 on current master, and additionally, still prints every warning in the main Budgie codebase that was printed with the global cflags.
=> Use meson warning_level instead of global warning flags

src/lib/manager.vala, src/lib/toplevel.vala, src/panel/com.solus-project.budgie-panel.gschema.xml, src/panel/manager.vala, src/panel/panel.vala, src/panel/settings/settings_panel.vala
This pull request adds a per-panel setting that defines the base spacing between applets, independent of CSS. This works via setting the spacing of each individual panel region, in addition to the spacing between the regions, so spacing between applets is consistent even at region boundaries. The default setting of 2 matches our current no-setting default, and the setting can be adjusted from a minimum value of 0 to a maximum value of 64.
The spacing is also adjustable in `panel.ini` via the `Spacing` key.
=> Per-panel setting for applet spacing

src/applets/notifications/NotificationsApplet.vala, src/applets/raven-trigger/RavenTriggerApplet.vala, src/daemon/endsession.vala, src/daemon/manager.vala, src/daemon/menus.vala, src/panel/manager.vala, src/polkit/polkitdialog.vala, src/raven/powerstrip.vala, src/wm/wm.vala
This PR fixes various compile-time Vala warnings with rewritten code. The different types of fixes are listed below.
- Replacing try/catch surrounding a `begin` call with a try/catch *within* a `begin` call - this is the intended way to catch errors thrown by async functions
- Removing (button_cancel) or commenting out (tab_sort) unused variables and functions
- Replacing the deprecated `popup` call with `popup_at_pointer`
- Using a null check rather than a try/catch with session manager registration, as this function never throws an exception and merely returns null on failure
- Using the `Gdk.Monitor` API for storing monitors and their geometry, along with storing the primary monitor
=> Fix various compile-time warnings in Vala code

src/daemon/notifications/dbus.vala
Per the Freedesktop Notifications spec, the `NotificationClosed` method must be called with two `uint32` types. Vala enum values are of type `int32`, and this can break applications. Simply changing the method signature seems to do the trick.
Validated by:
1. `dbus-monitor interface=org.freedesktop.Notifications`
2. `notify-send foo`
3. Seeing:
```
signal time=1651504477.875076 sender=:1.41 -> destination=(null destination) serial=77 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
uint32 2
uint32 2
```
Fixes #118
Fix `NotificationClosed` DBus signature to match the spec
=> Fixes spec compliance for closing notifications

.github/workflows/build.yml
Now that Ubuntu 22.04 has been released and GitHub Actions has a beta image for it, Budgie can build from within GitHub Actions. This PR adds a workflow to build Budgie on Ubuntu 22.04 with default options, except for use of GNOME Screensaver.
=> GitHub Actions workflow for Ubuntu 22.04

src/wm/wm.vala
Testing of various scaling changes across different monitor and graphic driver types shows that budgie desktop popovers and other elements of the GUI do not always refresh correctly.  As a quick win lets prompt the user to restart their session to allow the desktop to refresh & resize properly.
As an aside there doesn't appear to be any way to force mutter based dialogs to ensure messages span over more than one button.  Odd - just odd.
As discussed on matrix/development with @EbonJaeger - but tried to further reduce the message size to improve appearance without affecting potential translation understanding.
=> Improve scaling change message to request further user action.

src/daemon/notifications/dbus.vala, src/daemon/notifications/popup.vala
Some applications set a timeout of 0, which the spec says means that it should never expire. Our implementation doesn't really fit that, since persistence is done by Raven, not the notification server. So, we should have a minimum show time for the popups to ensure that one is actually shown when it should be.
Fixes #129
=> Set a mininum expiry timeout for notification popups

src/panel/panel.vala
Rather than adding applets directly to the panel on initial panel load, the `load_applets` function instead uses intermediate region lists sorted by the info's desired position. Once all applet info have been added to the region lists, each applet's info is updated with its actual position within the list, and is then added to the panel. This prevents issues with applets being uninstalled before being removed from the panel, and thus should resolve #72, along with other applet ordering issues that could be the result of initial race conditions.
=> Rewrite initial applet layout to prevent position desync

meson.build
Historically, Meson didn't know how to set c_std for a subproject at all. Meson 0.63.0 adds support for this, so the default_options kwarg to subproject now begins to respect this.
budgie-desktop uses c11, but artificially sets c89 for the gvc submodule. However, this does not actually work... the build then errors out when trying to build `subprojects/gvc/test-audio-device-selection.p/test-audio-device-selection.c.o`
Remove the faulty argument.
Fixes regression in commit 3d6d71c167dd9742cd072e7e6a3453c23ebb2658.
=> fix broken C std for gvc subproject

src/applets/icon-tasklist/IconTasklistApplet.vala
Rather than always removing a button wrapper in ITL when its group is replaced, this patch adds a check for whether or not the button is pinned. If it is, the applet instead removes the button's class group and first_app, then updates it visually, essentially cutting it off from the group change. Then the function proceeds normally, which creates a new button with the new group. For example, if the LibreOffice launcher is pinned and a document is opened within it, the LibreOffice launcher button will cease to show as "running", and a new button will appear for the application associated with that document.
Fixes #107.
=> Reset ITL buttons if group updated while pinned

src/appindexer/meson.build
Current built libraries have a budgie naming convention - either libbudgie* or libraven*.
This PR ensures the new appindexer library name is similarly names i.e. now libbudgie-appindexer
Tested by removing /usr/lib/libappindexer* and building the project from this branch.
Logging out and logging in produces no errors and the menu responds as expected to new/removed apps
=> Rename the appindexer library to have a consistent budgie naming convention

src/applets/budgie-menu/BudgieMenuWindow.vala, src/applets/budgie-menu/views/ListView.vala, src/applets/budgie-menu/views/View.vala
The previous `show()` function was only ever actually called when the widget is first shown. This adds a new abstract function for views to implement that gets called whenever the menu is opened, so any cleanup actions can be reliably performed.
=> Fix Budgie Menu view not resetting on open

src/session/meson.build
Patch used on UB.
Lets only merge this once we find out why the xsession reverseDNS name format in git sometimes does / sometimes does not work
=> Revert the xsession rename - closes #173

src/abomination/meson.build, src/appindexer/meson.build, src/applets/budgie-menu/meson.build, src/applets/clock/meson.build, src/applets/icon-tasklist/meson.build, src/applets/night-light/meson.build, src/applets/status/meson.build, src/applets/workspaces/meson.build, src/appsys/meson.build, src/daemon/meson.build, src/lib/meson.build, src/libsession/meson.build, src/panel/meson.build, src/polkit/meson.build, src/raven/meson.build, src/rundialog/meson.build, src/wm/meson.build
This commit adds all missing `gio-unix-2.0` dependencies on all targets that require it. This provides the `-I${PREFIX}/include/gio-unix-2.0` compiler flag, which fixes the following error:
This issue was already reported to other projects by the NixOS community: https://github.com/NixOS/nixpkgs/issues/36468.
This patch can be applied to the tarball released with version 10.6.3: https://github.com/FedericoSchonborn/budgie-overlay/blob/f7b6e707d183fc3f8ee31efb923249252cb9910f/packages/budgie-desktop/0001-Add-missing-gio-unix-2.0-dependencies.patch (it omits the `appindexer` directory, which isn't included in release builds).
=> Add missing gio-unix-2.0 dependencies

src/daemon/notifications/popup.vala
This makes notification popup bodies more consistent, and prevents them from taking up unnecessarily large portions of the screen.
The max chars were reduced slightly to ensure that the close button doesn't get shoved off the edge of the notification popup. Width chars were added so that the body text always has the same minimum and maximum size per line, so the entire popup body is filled by the label. Lines is set to 2, so only two lines of text is displayed. Note that this does not mean two lines in the popup; it's two lines of the actual notification text. This allows long lines to wrap (and wrapped lines don't count towards lines, because reasons) without popups taking up large amounts of screen real-estate. Xalign is set to 0 to ensure that the text always starts at the left …
=> Change label properties for notification bodies

src/applets/workspaces/WorkspacesApplet.vala
Replaces a `return true` with a `return false` in a critical Timeout callback so the function isn't repeated every 100ms.
Fixes #184, #183, #182, and #180.
=> Resolve numerous issues with the Workspace Applet

src/applets/clock/ClockApplet.vala
This was introduced in the glib2 pull request [!2698](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2698) and is not desired behavior for us.
Previous behavior restored by this PR:
Behavior introduced by the glib2 commit:
=> Remove numeric space in formatted clock applet output

src/daemon/xdgdirtracker/dbus.vala
For some reason, on Arch derivatives, XDG user dirs that aren't present or that resolve as symlinks are detected - but they resolve to the user's home dir instead. This compares the result of get_user_special_dir to the user's home dir path, and skips the XDG dir if they're equal.
=> Add extra check in XDG dir detection

src/appindexer/Application.vala
ThemedIcon can return invalid icons; this PR ensures fallbacks are used to prevent missing icon displays.
Closes: #205
=> Allow Applications Icons to use fallbacks

src/daemon/menus.vala
Draft - makes the window actionmenu display for most windows.
https://github.com/BuddiesOfBudgie/budgie-desktop/issues/176
Note - it uses the now deprecated Gtk.Menu.popup - I haven't figured out how to use one of the recommended alternatives.
ActionMenu doesn't appear on all windows - for example firefox esr or visual code (snap?)
We should also perhaps investigate removing the move workspace left/right menu items - should be able to-do that via the Gtk.Container remove methods at a guess. Remember the Wnck.ActionMenu is just a Gtk.Menu object
Anyway - marking this as draft.  **Feel free to improve** and eventually mark as ready.
=> Use idle and menu popup to display a Wnck ActionMenu

README.md
This was randomly irritating me so here I am. Unless there's some reason why it should be left at 2021, which there very well could be.
=> update copyright notice

src/appindexer/AppIndex.vala
Before attempting to enumerate `~/.local/share/desktop-directories`, check to make sure it actually exists. Resolves #232.
=> Check for existence of desktop-directories dir in appindexer

src/applets/workspaces/WorkspacesApplet.vala
The workspaces applet currently delays its refresh of the workspace item grid layout too late after the item size multiplier setting is changed, as seen here:
https://user-images.githubusercontent.com/12981608/209994673-fc4ae814-4f56-45b3-b04a-936592bedcc1.mp4
This patch queues a resize of each workspace item after the setting is changed, which allows for each item to refresh its grid properly, as seen here:
https://user-images.githubusercontent.com/12981608/209994794-91b2f7a1-1311-47b5-91c3-b5e5f95913ab.mp4
=> Queue resize of workspace item after size mult changed

src/appindexer/Application.vala
Some icon-themes do not have a application-default-icon defined.
Due to a quirk of fate our menu icon handling code was only testing
if the application icon "application-default-icon" was in the theme before
displaying it.
This PR now updates the logic to calculate if the application icon itself
is in the icon theme.
Verified using Moka icon theme 
1. Without the patch, using Moka and restarting the panel or logout/login the menu icons showed an empty icon
2. With the patch, Moka icons displayed correctly.  Even where Moka icons did not exist, the default application icon is displayed.
Note - we already set the application-default-icon fallback here https://github.com/BuddiesOfBudgie/budgie-desktop/blob/0eea3fdd3b1d98dbcd8699c8611bade46fe7a9f3/src/appindexer/Application.vala#L22
=> Set menu icon including where icon themes do not have a default

src/applets/status/PowerIndicator.vala
Fixes  #245
Fix issues with battery indicators on vertical panels. (Fixes 
- Fixes the orientation of the battery icons / labels so that on a left/right panel, a system with multiple batteries (i.e. a laptop with an internal and external battery) will display them vertically instead of horizontally. (avoiding an issue which causes the panel to expand beyond its expected size.
- Fixes an issue where if a 2nd battery is added to the system after the panel is running, the percentage label is displayed to the left of the icon instead of above it.
- [ x ] Squashed commits with `git rebase -i` (if needed)
- [ x ] Built budgie-desktop and verified that the patch worked (if needed)
=> Fix orientation with dual batteries

src/dialogs/power/dbus.vala, src/dialogs/power/window.vala
logind provides a method of detecting if hibernation is enabled on a system. This PR adds a check to the power dialog code that sets the sensitivity of the hibernation button conditional on whether hibernation is supported. Additionally, if hibernation is not supported, a tooltip is added to the button on hover that explains why the button is disabled.
=> Disable Hibernation button if the system doesn't support it

data/icons/README, data/icons/actions/budgie-menu-symbolic.svg, data/meson.build, src/panel/applets/budgie-menu/BudgieMenu.vala, src/panel/applets/budgie-menu/com.solus-project.budgie-menu.gschema.xml, src/panel/applets/budgie-menu/settings.ui
This pull request adds a new symbolic menu icon made from scratch. This new icon is only used if the user enables the new "Use Default Menu Icon" option in the Budgie Menu applet settings, or if the currently selected icon theme is in the following list: `["", "Adwaita", "HighContrast", "hicolor", "default"]`. 
The new icon was fully made from scratch using Inkscape. I've elected to license it under CC0 v1.0, and have mentioned this in the icons folder's README.
**New Icon**
**Papirus**
**Paper**
**hicolor**
Resolves #10.
=> Add new default menu icon

src/daemon/notifications/dbus.vala, src/daemon/notifications/popup.vala
Fixes a regression from #222 where the drop shadow on notification popups was cut off by the window border.
=> Fix notification drop shadow

src/panel/applets/budgie-menu/MenuItem.vala
Reduces the padding to the left of the icons in the Budgie Menu user dirs overlay.
=> Fix spacing in buttons in Budgie Menu overlay

src/panel/applets/budgie-menu/BudgieMenuWindow.vala, src/panel/applets/budgie-menu/OverlayMenus.vala
This PR adds function calls to hide Budgie Menu when clicking the Budgie Desktop Settings and System Settings buttons, as well as adding a missing item_clicked signal call in Overlay Menu for closure of Budgie Menu based on the connected function.
=> Fix missing hide calls and item_clicked emit on overlay menu.

src/daemon/org.buddiesofbudgie.budgie-desktop.screenshot.gschema.xml, src/daemon/screenshot.vala, src/daemon/screenshothome.ui
The sound can be quite loud compared to other application and system volumes, as I discovered yesterday when streaming release write-up. So let's have an option to have silent capture.
Also fixes some inconsistent alignment / indentation in the gschema.
=> feat: Add option to turn off the playback of screenshot capture sound.

src/daemon/screenshot.vala
This is a case of not cleaning one's glasses during implementation.
The screenshot window "..." shows the current keyboard shortcuts ... except the area and window labels are the wrong way around.  This PR switches around the labels.
=> Ensure screenshot popover labels match their corresponding keyboard shortcut

src/wm/screenshot.vala
Where invoking the screenshot and taking a window screenshot of an empty desktop, the image made is of a transparent (black) desktop displaying icons - screenshot (window) is actually a taking a screenshot of a hidden window.  
In this case we should take a full screenshot rather than of the transparent window.
Tested with nemo that manages the desktop icons - with this PR - a window screenshot no longer just takes a screenshot of a transparent window showing the desktop icons.  Turning off desktop icons support in BDS and making a screenshot (window) screenshots the whole desktop as well.
Note - there should only ever be either zero or one window of window-hint DESKTOP.  I can't think of a scenario why there would be multiple windows of window-type DESKTOP.
=> Test if the window of type desktop before taking a window screenshot.

meson.build
Currently, we check if git is installed, and then also check if git can retrieve a commit ID from the current directory. This is a teensy bit slow in case git is installed, but we are building from a tarball. Instead, do an in-process check whether .git exists, and if so then retrieving the git version is mandatory.
This:
- avoids inaccuracies or wasted time if we're not in a git repo
- makes it a fatal error if we're in a git repo but for deeply mysterious reasons decided to uninstall the git program
=> be more specific about checking for the git commit

src/panel/settings/settings_wm.vala, src/wm/com.solus-project.budgie.wm.gschema.xml, src/wm/screenshot.vala, src/wm/wm.vala
Fixes #298. This also cleans up some duplication of logic between screen-type screenshot and area, where screen is just an area of the dimensions of the screen.
Similar to GNOME Shell, we will dynamically disable undirect, before potentially re-enabling it (if it was not explicitly disabled in our settings before the call to screenshot).
Tested in the following games, all running in exclusive fullscreen mode, across several instances of both "screen" and "window" capture to validate that these aren't just one-offs that worked:
- Halo: Reach in MCC
- OpenMW
- Sid Meier's Civilization VI
All the above games were running in exclusive fullscreen modes.
=> fix: Inability to capture fullscreen applications like games.

src/raven/widgets/media-controls/mpris_gui.vala
Resolves an issue wherein KDE Connect could cause Raven to expand in size due to providing a long player identity.
=> Ellipsize overflowing text in Media Controls widget header

src/panel/settings/settings_raven_settings.vala, src/raven/com.solus-project.budgie.raven.gschema.xml, src/raven/notifications_group.vala, src/raven/notifications_view.vala, src/raven/raven.vala
Adds a setting to Budgie Desktop View to change the sorting order of notifications in Raven Notification View. The two options are from newest to oldest (default), and oldest to newest.
Closes #303
=> Implement setting to change sorting in Raven notification view

src/panel/settings/settings_panel.vala, src/panel/settings/settings_panel_applets.vala
Tweaks the layout and spacing of the panel applets/settings view to match the layout of the new Raven widgets/settings view.
=> Align panel settings layout with new Raven settings

src/raven/widgets/calendar/org.buddiesofbudgie.budgie-desktop.raven.widget.Calendar.gschema.xml, src/raven/widgets/sound-output/org.buddiesofbudgie.budgie-desktop.raven.widget.SoundOutput.gschema.xml
Somehow I mixed up the Calendar and SoundOutput settings schema contents. This PR just swaps them back around.
=> Fix SoundOutput and Calendar widget settings schemas

src/appindexer/RelevancyService.vala, src/panel/applets/budgie-menu/views/ListView.vala
This reworks the searching algorithm to use a [fuzzy Bitap](https://en.wikipedia.org/wiki/Bitap_algorithm) text matching algorithm for finding possibly relevant applications by name. This differs from the previous implementation (which only used basic Levenshtein distance across the entire strings) mainly in that it sees if the text to search contains any substring matching the search term.
To maybe make that easier to understand, searching for Budgie Control Center with the term "control" with the old algorithm would consider Budgie Control Center less relevant because it only calculates the distance of the entire string, whereas this algorithm ranks it more relevant because it does substring matching.
There are a few other smaller changes made in narrowing down the results:
- If an …
=> Relevancy algorithm refinements

src/panel/applets/budgie-menu/views/ListView.vala
This ensures all parts of Budgie Menu are visible when used on resolutions such as 1080p with 200% scaling, rather than parts of it being cut off.
=> feat: ensure Budgie Menu application lists height allocation accounts for GTK scaling factor

src/panel/applets/budgie-menu/OverlayMenus.vala, src/panel/applets/budgie-menu/views/ListView.vala
When the ListBox selection mode is set to `NONE`, keyboard navigation within Budgie Menu works, but there is no visual indicator. Changing it to `SINGLE` allows themes to show a visual indication that an item is selected, and that the arrow keys on the keyboard changes the selection.
=> budgie-menu: Change the selection policy from NONE to SINGLE

src/panel/applets/tray/TrayApplet.vala
#328 is caused by the tray applet attempting to fetch the watcher's DBus object before it's actually been registered to the bus, which is rare (as it has to happen IMMEDIATELY after the name is owned). This adds a 500ms timeout after the name is found, so the object has plenty of time to register itself.
=> Add timeout to watcher init in tray applet

src/daemon/screenshot.vala
This pull request fixes screenshot area selection on mutter 44.0-1ubuntu1/libmutter-12. We need to explicitly set `this.set_decorated(false)` in SelectLayer, to prevent the selection overlay to show decorators, resulting in a non-fullscreen overlay.
<Info on what this pull request adds>
=> Fix screenshot area-selection for libmutter-12

src/daemon/statusnotifier.vala, src/panel/applets/tray/TrayApplet.vala
This allows the panel to wait to attach to the host, while also ensuring that applications that start before the applet initializes can still register items. The wait before applet initialization has also been reduced from 500ms to 100ms.
=> Register a daemon-side SN host

.gitignore
clangd can be used with Visual Studio Code, and we definitely shouldn't be committing its cache.
=> Add clangd cache to gitignore

src/theme/meson.build
When compiling the built-in theme, check for the presence of the `sass` binary provided by `dart-sass`. If it's present, use that to compile SCSS - otherwise, fall back to the original behavior of using sassc. Resolves #343.
=> Look for dart-sass before sassc

src/panel/applets/budgie-menu/BudgieMenuButtons.vala, src/panel/applets/budgie-menu/views/ListView.vala
Previously, you could not navigate between categories in the Budgie Menu using only the keyboard. This cleans up the category button code as well as making them focusable, thus enabling keyboard navigation.
=> Make category buttons keyboard navigable

.github/workflows/build.yml, meson.build, src/wm/meson.build
This PR fixes zenity detection on OSes which do not have a new enough meson to have its `version()` check.
=> fix: check of zenity on OSes with older Meson

src/panel/applets/tray/DBusMenu.vala
This fixes segfaults caused by some apps that have tray icons. I believe that it happens due to bad implementations of the dbusmenu spec on the app side, which then cause the applet's internal record of the menu layout to be filled with invalid data. Solution is to completely ignore any items that don't have the correct type for the layout id (it should be int32), and also avoid showing menus without any items in them. This is reproducible with JetBrains Toolbox.
Needs review from @JoshStrobl, who I believe was seeing this happen with a different app.
=> Ensure that only valid nodes are added to tray item menus

src/theme/3.20/_main.scss, src/theme/common/_colors.scss, src/theme/common/_menu.scss
Replaces the color scheme currently in the Budgie built-in theme with the color scheme from the mockups of the complete theme rewrite. Neutral dark grey for background colors, Budgie green for selected buttons. Additionally, the Budgie Menu theming has been updated to fit that mockup.
=> Built-in theme recolor

src/abomination/abomination.vala
This adds a caveat to `is_disallowed_window_type`, where windows of type `WindowType.DIALOG` are only not shown if they're transient to a parent window. In combination with `is_skip_tasklist` and `is_skip_pager`, this should block most *actual* dialogs.
This resolves #266.
=> Workaround Private Internet Access not showing up in Icon Task List

src/dialogs/power/window.vala
This fixes the case where themes that don't style the dialog end up having a transparent background, making it very hard to see and use the dialog.
One thing to be aware of is that the previous way was done to combat focus issues when presenting the dialog under certain conditions. So far, though, I have been unable to get the focus to mess up with the new changes; the dialog is always focused correctly.
=> Remove style class changes in power dialog

src/appindexer/AppIndex.vala
These changes are based on user feedback and just having used the current category sorting for an extended period of time. Applications that previously were put into the Other category fit better in other existing categories. Some of the 
application exclusions just no longer make sense.
This category has been removed entirely. It had a weird overlap with the System Tools category, and it wasn't clear what the difference was between Utilities and Accessories, leading to confusion. To address this, items that used to be in the Utilities category will now be included in the System Tools category.
=> Change the sorting of some applications and categories

src/daemon/notifications/dbus.vala, src/daemon/screenshot.vala
The two cases are handled differently, as screenshots use gstreamer and notifs use canberra.
The screenshot sound now has a timeout of 2 seconds, after which it will cancel the attempt to play the sound and just move forward with the screenshot. This may cut off longer screenshot sounds, but it doesn't cut off the default.
The notif sounds are now launched as threads, so they don't block the main thread when queued up. This means that all buffered notif sounds will play upon the default sink being unlocked, but this is how all other sound players work, so it's not a big deal.
=> Prevent notifs and scrshot from locking up when sink is locked

src/appindexer/RelevancyService.vala, src/appindexer/fuzzer/fuzzer-1.0.vapi, src/appindexer/fuzzer/fuzzer.c, src/appindexer/fuzzer/fuzzer.h, src/appindexer/fuzzer/meson.build, src/appindexer/meson.build
When transpiling to C, Vala really mangles this function, causing it to crash randomly on non-Latin text. Porting it to C and checking it against the reference implementation found online fixes the crashing issue while (as far as I can tell with Spanish) still producing the desired search results.
Another consideration was converting the search text and compare text to ASCII. This method also seems to fix the issue, though it feels more dirty. I decided to go forward with the C port because I simply can't trust Vala to do the right thing when it comes to this function.
Fixes #383
=> Port the fuzzy scoring function to C

src/daemon/notifications/dbus.vala, src/daemon/settings.vala, src/panel/applets/notifications/NotificationsApplet.vala
Use ngettext plural support to allow proper translations.
=> Use ngettext for plural strings

src/panel/applets/trash/trash_applet.c, src/panel/applets/trash/trash_info.c, src/panel/applets/trash/trash_info.h, src/panel/applets/trash/trash_item_row.c, src/panel/applets/trash/trash_item_row.h, src/panel/applets/trash/trash_manager.c, src/panel/applets/trash/trash_popover.c
As long as we have valid GFile objects, file operations won't fail. The trick is getting correct GFiles when initially scanning the trash directory, because GLib in its infinite wisdom makes GFileEnumerator return a list of GFileInfo, not GFile. And file name/path URI encoding is a mess.
Tested with:
- Files with % in the name, both on local and removable drives
- Files without % in the name, both on local and removable drives
- Files with spaces in the name, both on local and removable drives
- Files without spaces in the name, both on local and removable drives
- Files only consisting of letters, both on local and removable drives
Tested by:
- Drag-n-dropping file to trash applet button
- Trashing file in file manager
- Permanently deleting file via applet
- Restoring file via applet …
=> trash-applet: Try to use GFile wherever possible

src/panel/applets/keyboard-layout/KeyboardLayoutApplet.vala
IBus already gets initialized in wm, and calling that function here causes severe breakage, leading to budgie-panel being repeatedly killed for OOM.
=> keyboard-layout: Don't try to initialize IBus

src/panel/applets/tray/DBusMenu.vala, src/panel/applets/tray/DBusMenuNode.vala, src/panel/applets/tray/TrayItem.vala
Adds a quirk for tooltips of type string (TeamViewer). That resolves #429.
Also adds some additional checks for containers to potentially work around #437.
=> Work around more SN/dbusmenu quirks

data/budgie-portals.conf, data/meson.build
Defaults to xdg-desktop-portal-gtk for all portals. Resolves #436. xdg-desktop-portal v1.17.0 isn't stable, so this PR is untested.
=> Add xdg-desktop-portal config

src/appindexer/RelevancyService.vala
Attempt to address #347 #421 
Performs fuzzy search on name, generic name and keywords and uses the best result as score.
Also adjusted the threshold to include more relevant applications since some were previously excluded even though the app name included the search keyword.
=> Take keywords and generic name into account for relevancy

src/daemon/settings.vala
Adds a few LoC into the daemon that synchronize the dark theme dconf setting with GNOME's freedesktop color scheme dconf setting.
=> Make dark theme switch apply to color scheme pref

src/panel/applets/tray/TrayApplet.vala, src/panel/applets/tray/com.solus-project.tray.gschema.xml, src/panel/applets/tray/settings.ui
Icon scaling in the system tray is now disabled by default, and can be enabled by the associated switch in the applet settings. Resolves #435.
=> Add setting for tray icon scaling

src/panel/applets/tray/DBusMenuNode.vala
No idea why, but sometimes properties are boxed inside variants and need unboxing before they can be used. When a property is updated, if the value is a variant type, attempt to unbox it first up to a limit of 8 times. Resolves #451.
=> Attempt to unbox primitives for DBusMenu nodes

src/daemon/notifications/popup.vala, src/lib/notification.vala, src/panel/com.solus-project.budgie-panel.gschema.xml, src/raven/notifications_group.vala, src/raven/notifications_view.vala, src/theme/common/_raven.scss
This does a couple of things. First, when constructing a notification group, just get the image directly from our Notification object. We did all the work to get the correct image, let's actually use it.
Secondly, remove our HashTable mapping application name to notification group. We don't need it; anything it was used for we can get from the ListBox. This avoids having to keep track of groups in multiple data structures (the table and the list box). This makes the code easier to maintain, and slightly more memory efficient.
The NotificationGroup widget has been changed to a `Gtk.ListBoxRow` to make it easier to find and remove groups from the view.
Lastly, switch to `ngettext` to build the text for the notification view header instead of an if/elseif chain.
Fixes #450
=> Simplify Raven notification group

src/panel/applets/tray/TrayApplet.vala
=> Fix initial tray icon scaling

src/lib/notification.vala
The notification spec states that the `desktop-entry` hint should be the prefix of the Desktop Application Info file. However, because of the push to have fully-qualified app ID's, some applications now have a mismatch between the ID and the desktop file, meaning the hint cannot be used for that application.
In cases where the hint fails, try to guess the ID using the application's name given to us from DBus.
It seems to fix https://github.com/BuddiesOfBudgie/budgie-desktop/issues/477.
The spec states that the image data from a notification should be used before the application icon or any other icon. This change should reflect that.
It seems to fix #477. Nemo and Twitch Streamlink notifications now display properly in Raven on my system.
Signed-off-by: Evan Maddock …
=> notifications: Try to guess app id if getting from hints fails

src/daemon/screenshot.vala
Screenshot uses a temporary folder path to save image data between the client and server dbus elements.
This PR ensures a user-space location is used rather than a system location.
=> Use user-space variables to pass temporary screenshot data

meson.build, meson_options.txt, src/dialogs/meson.build, src/dialogs/sendto/Application.vala, src/dialogs/sendto/Dialog/BaseDialog.vala, src/dialogs/sendto/Dialog/DeviceRow.vala, src/dialogs/sendto/Dialog/FileReceiver.vala, src/dialogs/sendto/Dialog/FileSender.vala, src/dialogs/sendto/Dialog/ScanDialog.vala, src/dialogs/sendto/Services/Adapter.vala, src/dialogs/sendto/Services/Device.vala, src/dialogs/sendto/Services/Manager.vala, src/dialogs/sendto/Services/ObexAgent.vala, src/dialogs/sendto/Services/Session.vala, src/dialogs/sendto/Services/Transfer.vala, src/dialogs/sendto/meson.build, src/dialogs/sendto/org.buddiesofbudgie.sendto-daemon.desktop, src/dialogs/sendto/org.buddiesofbudgie.sendto.desktop, src/panel/applets/status/BluetoothClient.vala, src/panel/applets/status/BluetoothDBus.vala, src/panel/applets/status/BluetoothIndicator.vala, src/panel/applets/status/BluetoothObexManager.vala, src/panel/applets/status/StatusApplet.vala, src/panel/applets/status/meson.build, src/theme/common/_bluetooth.scss, src/theme/common/_imports.scss, src/theme/meson.build
The Bluetooth rewrite is finally here! GNOME Bluetooth is entirely dropped from Budgie Desktop; we now use Bluez and UPower directly, giving us full control over how Bluetooth is interacted with. You will now be able to connect to and disconnect from your Bluetooth devices from the panel without having to go to the Control Center. You will still have to visit the Control Center to pair new devices, however. With the direct usage of UPower, you will also see the battery power of devices that report it right in the applet popover.
This also includes our own implementation of Sendto in order to send and receive files over Bluetooth. Budgie Sendto is very heavily inspired by Elementary's own Bluetooth Sendto implementation. It runs in the background to listen for file transfer requests from …
=> Implement a new Bluetooth indicator

src/dialogs/sendto/meson.build
Install the sendto autostart file to the correct stateless directory if statelessness has been enabled.
=> sendto: Use stateless XDG autostart directory if stateless is set

src/daemon/tabswitcher.vala, src/panel/applets/workspaces/WindowIcon.vala
1. Fixed workspace-based rendering by adding missing invalidate filter during construction.
2. Fix focus issue caused by our get_time providing an incorrect event timing. Resolved by using Gdk.X11.get_server_time, need to rip that out when we switch to Wayland.
3. Fix TabSwitcher sizing not updating
Fixes:
- #515
- #517
=> fix: multiple tabswitcher bugs (workspace-based rendering, focus, oversizing)

.github/workflows/build.yml, meson.build, meson_options.txt
1. ubuntu CI failing due to too old of a upower. When new LTS is out we can add it back.
2. rawhide will help to identify breaking changes due to new toolchains.
3. actually get CI again.
=> Switch to Fedora rawhide for CI

src/panel/applets/workspaces/WindowIcon.vala
Removed unnecessary (and borked) check. Should have been `!==` but not really needed anyways. It won't do anything if the window is already active on the current workspace, so the entire check is extraneous.
=> Fix workspace applet window icon click not performing workspace switch

src/panel/applets/tray/TrayItem.vala
Fixes Cinny and Tauon tray icons when run outside Flatpak. This cannot fix apps within Flatpak, as their icon paths are only valid within the sandbox.
=> Work around even more SNI noncompliance

src/panel/applets/workspaces/WorkspacesApplet.vala
…oses #541)
Use Enum DOWN instead of LEFT to scroll in a left-wards direction
Closes #541
This is definitely odd.  Looking at libxfce4windowing it does appear that their enum for motion direction is mapped correctly to wnck's values and our vapi is mapped to libxfce4windowing correctly.
So why using DOWN rather than LEFT works feels just wrong ... but works.  Just feels like there is a bug somewhere but not sure where.
=> Use Enum DOWN instead of LEFT to scroll in a left-wards direction

meson.build
In Meson 1.4.0, warnings for Vala-transpiled C code were unhidden, which causes the Budgie build to turn into unreadable logspam due to the absolutely abysmal C code generated by Vala. This PR restores the prior behavior by disabling all warnings for C code.
Let it be known that I didn't want to have to do this and would have fixed the code myself. *If I could have.*
=> Disable C compiler warnings entirely

src/dialogs/run/RunDialog.vala
<Info on what this pull request adds>
Added a cli option to disable `focus_quit` that would close `budgie-run-dialog` when loosing focus. Without the argument it's set to `false`, leaving the default behavior unchanged.
```
Application Options:
-f, --focus-keep     Do not quit when out of focus
```
CLI options parsing was implemented the same way `sendto` `Application.vala` does it.
=> feat: cli option for focus_quit field #424

src/windowing/window_group.vala
Sets the previous active window in a group to another window when a window is closed. This prevents button focus and activation issues when a window in a group is closed.
Fixes https://github.com/BuddiesOfBudgie/budgie-desktop/issues/565
=> windowing: Set a new last active window when the last active window is closed

src/appindexer/AppIndex.vala
Enables the showing of terminal applications in the Budgie Menu.
Fixes https://github.com/BuddiesOfBudgie/budgie-desktop/issues/554
=> budgie-menu: Show terminal applications in the menu

src/daemon/tabswitcher.vala
When pressing Alt-Tab with no active windows, the tabswitcher window still appears. No icons are displayed and the window title is either blank, or the last window selected via alt-tab. It appears this is due to the window being set to show on the keypress regardless of the number of active children.
This PR would address this by making the "get_visible_children" public so the DBus function can check if there are items in the tabswitcher window before showing the window. Since this function already takes into consideration the "Show all windows in tab switcher" setting in BDS, it ensures the tab switcher will still work correctly with this setting on or off.
Closes #578
=> Don't show tabswitcher if window is empty

src/daemon/endsession.vala
Fix the end session dialog blocking the authentication dialog when a password is required to shut down the computer.
The fix was to hide the shutdown dialog when the "Shutdown" button is clicked.
=> Fix end session dialog blocking authentication dialog

src/panel/applets/icon-tasklist/IconTasklistApplet.vala, src/panel/applets/icon-tasklist/widgets/IconButton.vala
In some cases, opening an application, closing it, and re-opening it again from a pinned launcher would fail to update the launcher button; it would just be stuck doing the waiting animation, despite the application and a window appearing. This is because on X11, you pretty much have to just guess at what the desktop ID is for an application. We do this using the application's name, which may not be in the correct letter casing. This leads to the tasklist searching for, e.g., Nemo.desktop when you really want nemo.desktop.
To get around this, first check using the same ID we did before. If that doesn't work, try again with converting the guessed ID to lowercase.
=> icon-tasklist: Fix some pinned launchers not properly updating when opened

src/panel/applets/icon-tasklist/widgets/IconButton.vala
When Icon Tasklist is on a right panel, a diagonal line shows through the active item.
This PR just tweaks this to make the indicator line vertical.
Closes #592
=> fix tasklist indicator line on right panel

src/panel/applets/trash/meson.build
link_libpanelenum is not currently listed in applet_trash_deps. Although this builds just fine on systems using meson with ninja, this will result in build failure on systems that use meson with samurai, outputting the following error message:
```
In file included from .. /src/panel/applets/trash/trash_plugin.h:14,
from /src/panel/applets/trash/trash_plugin.h:15:
../src/plugin/panel/plugin.h:16:10: fatal error: budgie-enums.h: no such file or directory 
```
This error can be especially problematic on distros like Alpine Linux which only ship samurai in the main repositories. Apparently, this is due to a difference in how ninja and samurai schedule build edges (see [Meson Issue #9937](https://github.com/mesonbuild/meson/issues/9937#issuecomment-1029293627) & [samurai differences from …
=> Add missing dependency to 'trash' applet meson.build

meson.build, src/daemon/tabswitcher.vala, src/panel/applets/workspaces/WindowIcon.vala, vapi/libxfce4windowing-0.vapi
v4.19.8 includes an API break for the activate method which this PR resolves.
https://gitlab.xfce.org/xfce/libxfce4windowing/-/merge_requests/55
If we find passing NULL isnt adequate then we'll need to fiddle with the Seat changes as per the MR above
Separately I'll raise a PR on main for a larger set of changes once I've tested the PR against magpie v1 and labwc
=> Adapt to libxfce4windowing v4.19.8

src/daemon/background.vala, src/daemon/manager.vala, src/daemon/meson.build
OK, was bored with black backgrounds
This PR basically moves the existing background handling but now is invoked by budgie-daemon.
The background is drawn using swaybg so this introduces that as a runtime dependency.
It's built on the xf4w v4.19.8 branch.
=> Background handling via swaybg

src/bridges/labwc/labwc_bridge.py, src/bridges/labwc/menu.xml, src/bridges/labwc/meson.build
This PR adds a root menu where no desktop icons is used.
The bridge has been updated to copy the menu from the installed shared folder - or from the distro- equivalent if a distro wants their own custom folder.
Translations for the menu labels are handled as well on the startup of the bridge.
Note - the old menu code will be deleted in a separate PR in-coming via the osdkeys branch
=> Add a root menu for the desktop

src/windowing/meson.build
This is another instance of #185. Since we are [using `DesktopAppInfo` directly](https://github.com/search?q=repo%3ABuddiesOfBudgie%2Fbudgie-desktop+DesktopAppInfo+path%3A%2F%5Esrc%5C%2Fwindowing%5C%2F%2F&type=code), let's add `gio-unix-2.0` explicitly.
=> meson: Explicitly add gio-unix-2.0

src/bridges/labwc/rc.xml, src/daemon/notifications/dbus.vala
This PR changes from absolute positioning of windows (aka X11) to layershell positioning
=> Rejig notifications to work with layer-shell positioning

src/session/budgie-desktop-labwc.desktop.in.in, src/session/budgie-desktop-magpie.desktop.in.in, src/session/budgie-desktop.desktop.in.in, src/session/meson.build
Switch the sessions to make labwc the default for the 10.10 release.
Leave the magpie session in the code, but commented out.  We can later reinstate this as a default as and when needed.
=> Switch session files, leave magpie session in the code for a future release

src/panel/applets/icon-tasklist/widgets/ButtonPopover.vala
Removes the last remaining reference to XID in Icon Tasklist.
=> icon-tasklist: Remove last references to xid

src/dialogs/polkit/polkitdialog.vala
This ensures the polkit window editable field is focused.
Note - it appears that wlroots based compositors need the user to run the following to allow polkit windows to have the permissions to actually execute what pkexec wants to run for xwayland apps.
xhost + local:
Without the above in journalctl you see the following:
Authorization required, but no authorization protocol specified
There maybe some other secret sauce here get the extant polkit code to-do this for the user, but I don't know what this wouldbe.
=> Add on-demand to the polkit window to ensure entry field is editable

meson.build, src/daemon/gammastep.config, src/daemon/manager.vala, src/daemon/meson.build, src/daemon/nightlight.vala
Adds nightlight support using gammastep.
budgie-daemon watches for settings-daemon.color changes.  On any change, a gammastep.config file is used to define what values should be used.
This config files exists in /usr/share/budgie-desktop and like the labwc bridge, config files can be overridden by a distro- prefix to the config file name.
By using a config file, all gammastep configuration options can be modified by a user - with the exception of the key-pairs managed directly by the daemon.
=> Add nightlight support using gammastep - closes #649

src/panel/applets/workspaces/WindowIcon.vala, src/panel/applets/workspaces/WorkspaceItem.vala, src/panel/applets/workspaces/WorkspacesApplet.vala
This PR does a few things for the workspace applet:
- Removes any reference to BudgieWM, since that is no longer used.
- Removes any remaining Wnck/xid code.
- Fixes a crash when a window is opened.
- Makes the add workspace button unlickable if a new workspace cannot be added.
The only other outstanding issue that I know of so far is that hovering the mouse over the add workspace button when it's set to only show on hover causes the revealer to keep opening and closing in rapid succession for as long as the mouse is there.
This should fix #470. If any further refinements are needed, they can be done later in separate PRs.
=> fix: workspace applet wayland support

src/panel/applets/notifications/NotificationsApplet.vala
Enables the ability to toggle the DoNotDisturb state by middle-clicking on the notification applet icon on a panel.
=> notifications: Toggle Do Not Disturb state when middle-clicking the applet icon

src/daemon/nightlight.vala
nightlight copies a default config from a system location to a local folder.
Normally this is ok on a first login.  
However, this local folder may already exist if gammastep is in use from another DE.
So lets test to see if the folder actually exists before trying to create the gammastep folder... thus allowing the budgie config to be successfully copied into the gammastep folder
=> Test to see if the gammastep local folder actually exists before creating it

src/panel/applets/icon-tasklist/meson.build, src/panel/meson.build, src/raven/meson.build, src/raven/raven.vala, src/windowing/meson.build
This removes various X11 specific compilation issues - mostly library usage.
Quick look, AppSys and tasklist applet are the key remaining areas still requiring X11 based code.
Have had a look around and I don't see any obvious issues by removing this stuff.  
Worth a second/third pair of eyes
=> Cleanup X11 compiler usage

src/wm/20_solus-project.budgie.wm.gschema.override
Use  the pre- overlay-key value to prevent magpie window manager crash when mutter-common v48-rc is installed
=> Add override for overlay-key to prevent crash with mutter-common v48-rc

src/panel/plugin_manager.vala
This is required to prevent old plugins crashing the panel due to API/ABI changes
=> Bump the plugin version since the API/ABI has been updated

src/bridges/labwc/labwc_bridge.py
as per xfce4-session they use a config file specific to xfce4 i.e. ~/.config/xfce4/labwc
Lets be labwc friendly and similarly use a DE specific folder i.e. ~/.config/budgie-desktop/labwc
At the same time fix a crash on first startup where we were trying to translate the system menu.xml file (causing a permissions failure) rather than the freshly copied local menu.xml which can be written to.
=> use budgie friendly folder for our labwc config file

src/panel/settings/settings_wm.vala
as per the title - BDS - Windows options are not relevant for 10.10
=> Removal modal dialog and unredirect support since these are mutter specific

src/windowing/meson.build
Similarly for other code library usage (plugins, themes, panels etc), this defines a shared library for the windowing codebase to allow Debian (and possibly others) something to link against. 
The effect of this change is to have a functional icon-tasklist with new windows appearing as icons.
=> Use a static shared-library for the windowing capability to ensure chroot based packages have something to link against

src/bridges/labwc/labwc_bridge.py
This removes the budgie-desktop part of where the labwc config file was saved to in #690.
My bad - I forgot to test with removing the original ~/.config/labwc
You'll note that when you do this, labwc doesnt actually use ~/.config/budgie-desktop/labwc
Changing /usr/share/wayland-sessions/budgie-desktop.desktop to use the command line entry "-C ~/.config/budgie-desktop/labwc/" to execute labwc doesn't appear to work.
I don't know why - possibly a bug in labwc ... or cannot use it in conjunction with -S /usr/bin/budgie-desktop
For the moment - lets revert the change until we find a better answer / an alternative way to specify the labwc configuration folder.
Using an environment variable XDG_CONFIG_HOME as per https://forum.xfce.org/viewtopic.php?id=18013 would impact all apps config files. …
=> Partial revert of #690

data/budgie-portals.conf
This specifies that the wlroots xdg-desktop-portal backend should be used for sharing the screen.
Tested by trying to share just a screen or just a window in Discord, and seeing that it works.
=> data: Specify the wlroots portal backend for screensharing

src/dialogs/screenshot/budgie-screenshot-dialog.desktop.in.in, src/dialogs/screenshot/screenshot.vala, src/session/budgie-desktop-screenshotdialog.desktop.in.in
We are expecting too much of libxfce4windowing to get the monitor and scale details on startup - the underlying wayland client needs more time after the desktop has initialised. This is intended to prevent crashing if the necessary details are not found before first usage. As a fallback, the autostart session is amended to restart if necessary if at anytime the dialog fails for any reason.
Taken together this makes the screenshot capability experience more robust
=> Make the screenshot dialog less aggressive to start when finding libxfce4windowing details.

src/dialogs/polkit/dialog.ui, src/dialogs/polkit/polkitdialog.vala
See the headline
In summary - if just one authentication user is found then display the name via a centered label.  
Currently, if just one authentication user is found the name was hidden.
This ensure that even if a standard account is being used, the standard user will know they should be authenticating using the primary administrator.
=> Always display the authentication user using a label if there is just one account - closes #624

src/daemon/notifications/dbus.vala, src/daemon/notifications/popup.vala
as per #700 - this ensures only one action is ever invoked per popup
Note - this PR also fixes an obvious spelling issue for a member function
=> Only invoke one action per popup - closes #700

src/dialogs/screenshot/screenshot.vala
1. Pressing escape now closes the window on the initial screenshot window or navigates back to the initial screenshot window if on the post screenshot window
2. default focus widget is now the screenshot button for the screenshot window
3. default focus widget is now the save button for the post screenshot window
2 & 3 means you can just press enter twice to take a screenshot and save it without using the mouse.
=> Make screenshot more keyboard friendly with sane defaults - closes #611

src/panel/applets/icon-tasklist/widgets/ButtonPopover.vala
Trying to hide a popover that's been deleted is bad, m'kay?
Fixes https://github.com/BuddiesOfBudgie/budgie-desktop/issues/658
=> icon-tasklist: Fix crash when icons are removed

src/raven/widgets/usage-monitor/usage_monitor.vala
=> Ensure usage levelbar granularity is set to 0px so that bar values display correctly - closes #735
