BuddiesOfBudgie/budgie-desktop

- src/applets/workspaces/WorkspacesApplet.vala
- src/daemon/endsession.ui
- src/polkit/dialog.ui
- src/theme/3.20/_main.scss
- src/theme/3.20/theme.scss
- src/theme/common/_dialogs.scss
- src/theme/common/_notifications.scss
- src/theme/common/_panel.scss
- src/theme/common/_workspaces.scss
- src/theme/common/widgets/_base.scss
- src/theme/meson.build
Will resolve #44.
Not every widget has been restyled - all popovers except the Budgie Menu have been left alone due to difficulty with styling.
> Fix Current Internal Theme

- src/raven/notifications_view.vala
With the rewrite, it looks like the signal to clear notifications was never connected.
This makes the `Meta+C` key bind work again.
Fixes #75
> Re-connect to the Raven signal to clear all notifications

- src/applets/budgie-menu/BudgieMenu.plugin.in
- src/applets/caffeine/CaffeineApplet.plugin.in
- src/applets/clock/ClockApplet.plugin.in
- src/applets/icon-tasklist/IconTasklistApplet.plugin.in
- src/applets/lock-keys/LockKeysApplet.plugin.in
- src/applets/night-light/NightLight.plugin.in
- src/applets/notifications/NotificationsApplet.plugin.in
- src/applets/places-indicator/PlacesIndicator.plugin.in
- src/applets/raven-trigger/RavenTriggerApplet.plugin.in
- src/applets/separator/SeparatorApplet.plugin.in
- src/applets/show-desktop/ShowDesktopApplet.plugin.in
- src/applets/spacer/SpacerApplet.plugin.in
- src/applets/status/StatusApplet.plugin.in
- src/applets/tasklist/TasklistApplet.plugin.in
- src/applets/tray/TrayApplet.plugin.in
- src/applets/user-indicator/UserIndicator.plugin.in
- src/applets/workspaces/WorkspacesApplet.plugin.in
Instead of just duplicated titles, actually describe what each applet does.
> Update descriptions for built-in applets

- src/applets/raven-trigger/RavenTriggerApplet.vala
Uses a Mutex for synchronization of prop and anchor changes. This SHOULD have the same result as the prior code, but without using deprecated functions to force synchronous behavior.
> Use a Mutex for Raven threading

- src/daemon/notifications/dbus.vala
Instead of using GTK's estimation for the size our popup window will be, we attach to the size_allocate signal and show the popup before setting its position. Once size_allocate is called, the proper size of the notification is known, and we can immediately move it to the correct position before the screen is updated with the notification visible. This makes the behavior of the bottom-left and bottom-right notification positions match the behavior of the top-left and top-right positions.
Fixes #139.
> Set notif popup position after size allocation

- src/applets/status/PowerIndicator.vala
> Fix PowerIndicator spam by only emitting warning once.

- src/applets/workspaces/WorkspaceItem.vala
- src/applets/workspaces/WorkspacesApplet.vala
- src/applets/workspaces/com.solus-project.workspaces.gschema.xml
- src/applets/workspaces/settings.ui
Provides 0.5x, 0.75x, 1.0x, 1.5x, and 2.0x sizes. Defaults to 1.0x.
Resolves #163.
> Add setting for workspace item size

- src/applets/workspaces/WindowIcon.vala
> Update workspace item icons when window icon changes

- src/applets/workspaces/WorkspacesApplet.vala
- src/applets/workspaces/com.solus-project.workspaces.gschema.xml
> Switch from string parsing to enum values for workspace item size

- src/daemon/notifications/dbus.vala
Return early in the notification handler if a popup shouldn't be shown. This prevents creating (and showing) a window, even if the popup window isn't visible.
Because of Raven, we can't just return the ID. Instead, dispatch the notification and then close it as Expired right after.
Note that this may only fix a regression from #222, and not from 10.6.
Fixes #256
> Return early if a popup shouldn't be shown

- src/panel/settings/settings_plugin_chooser.vala
> Plugin chooser: escape description markup symbols

- src/dialogs/polkit/polkitdialog.vala
> Prevent polkit dialog from being resized

- src/panel/settings/settings_style.vala
> Enable ellipsize for Style boxes in BDS

- src/panel/applets/status/PowerIndicator.vala
> power-indicator: add controls for power mode via power-profiles-daemon

- src/panel/applets/status/PowerIndicator.vala
- src/panel/applets/status/StatusApplet.vala
- src/panel/applets/status/com.solus-project.status.gschema.xml
- src/panel/applets/status/settings.ui
> move battery label setting to Budgie Desktop Settings

- src/abomination/AppGroup.vala
- src/abomination/abomination.vala
- src/daemon/tabswitcher.vala
- src/panel/applets/icon-tasklist/IconButton.vala
- src/panel/applets/icon-tasklist/IconTasklistApplet.vala
- src/panel/applets/places-indicator/PlacesIndicatorWindow.vala
- src/panel/applets/tray/DBusMenu.vala
- src/panel/applets/workspaces/WorkspaceItem.vala
- src/panel/applets/workspaces/WorkspacesApplet.vala
- src/panel/manager.vala
- src/panel/panel.vala
- src/raven/main_view.vala
- src/raven/widgets/sound-input/sound_input.vala
- src/raven/widgets/sound-output/sound_output.vala
This is finally possible now that we no longer use our own generated Vapi files for GLib.
> Use is_empty() instead of length checks on collections

- README.md
- src/session/budgie-desktop.in
Updates the readme and version string.
> Update Copyright Years

- src/panel/applets/status/PowerIndicator.vala
> Move below initialization of radio buttons

- src/panel/applets/tray/TrayItem.vala
The person who wrote the code to add custom icon theme paths in our Status Notifier implementation (whoever that may be) wrote some code that only works by sheer chance. This PR adds PROPER support for custom icon theme paths, and should resolve any issues with laggy panels that were caused by the prior implementation.
> Fix oversight in custom icon theme path reading

- src/session/budgie-desktop.in
Start requiring budgie-session for 10.9 and beyond.
> Start requiring budgie-session

- src/dialogs/run/RunDialog.vala
> Set budgie run dialog to skip pager and taskbar

- src/daemon/tabswitcher.vala
- src/panel/applets/workspaces/WindowIcon.vala
- src/panel/applets/workspaces/WorkspaceItem.vala
- src/panel/applets/workspaces/WorkspacesApplet.vala
- vapi/README.md
- vapi/libxfce4windowing-0.deps
- vapi/libxfce4windowing-0.vapi
Updates the XFW vapi to 4.19.3, which has some breaking changes.
Fixes #546
> vapi: Update libxfce4windowing to 4.19.3

- src/dialogs/polkit/meson.build
- src/dialogs/polkit/polkitdialog.vala
as per the title - without this our polkit dialog is displayed at a random position on the screen.
> Center the polkit dialog

- .github/workflows/build.yml
> CI: Fix systemd issue in rawhide

- src/plugin/panel/popover.c
> budgie-popover: Add missing NULL terminator to g_object_new

- src/bridges/labwc/labwc_bridge.py
- src/bridges/labwc/rc.xml
bridge support for edge-tiling configuration in BDS
> Add support for edge tiling configuration

- src/daemon/osdkeys.vala
- src/daemon/settings.vala
Resolves https://github.com/BuddiesOfBudgie/budgie-desktop/issues/704
Also ensures that if we have caffeine boost with max brightness, that this doesn't inadvertently invoke the brightness OSD to display
> Handle caffeine boost notifications and brightness changes

- src/panel/manager.vala
We can't get a window's geometry under Wayland, so instead, try to get
the "primary" monitor from the first Budgie panel we find, and check if
a window's monitor is the same.
It may be janky with workspaces, since we can't yet do
Window<->Workspace association with libxfce4windowing and labwc, but
otherwise, it *seems* to work. Kind of amazing, really.
> panel: Don't use geometry to detect monitor

- src/bridges/labwc/labwc_bridge.py
- src/bridges/labwc/rc.xml
> Bridge the icon-name so that window icons match - closes #727
